#!/bin/bash

# install from USB
# enable full disk encryption

# enable touchpad tapping
# edit /usr/share/X11/xorg.conf.d/*-libinput.conf
# Section "InputClass"
#         Identifier "libinput touchpad catchall"
#         MatchIsTouchpad "on"
#         MatchDevicePath "/dev/input/event*"
#         Driver "libinput"
#         Option "Tapping" "True"
#         Option "PalmDetection" "True"
#         Option "TappingDragLock" "True"
# EndSection

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install \
     curl deborphan docker.io emacs-lucid \
     erlang-common-test erlang-eunit erlang-dialyzer \
     erlang-mode erlang-parsetools erlang-dev \
     feh git htop jq make mosh ncdu netcat-traditional \
     openssh-server pass plasma-workspace-wayland powertop tmux

sudo snap install chromium spotify

# get my stuff
[ ! -e ~/.git ] &&
    cd /tmp && \
	rm -rf dotfiles.kubuntu && \
	git clone https://github.com/massemanet/dotfiles.kubuntu && \
	cd dotfiles.kubuntu && \
	git remote set-url origin git@github.com:massemanet/dotfiles.kubuntu && \
	mv /tmp/dotfiles.kubuntu/.git ~
(cd && git reset --hard)

# emacs (cask)
[ ! -d ~/.cask ] && \
    curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
(cd ~/.emacs.d && ~/.cask/bin/cask install)

# keybase
curl -s https://prerelease.keybase.io/keybase_amd64.deb -o /tmp/kb.deb
sudo dpkg -i /tmp/kb.deb
sudo apt-get install -fy

