#!/bin/bash

sudo apt-get update && \
sudo apt-get upgrade -y && \
sudo apt-get install -y \
     curl deborphan emacs-lucid \
     erlang-common-test erlang-eunit erlang-dialyzer \
     erlang-mode erlang-parsetools erlang-dev \
     feh g++ git htop i3 jq libnotify-bin \
     make mosh ncdu netcat-traditional nodm \
     openjdk-8-jdk-headless openjdk-11-jdk-headless openssh-server \
     pass pgadmin3 powertop \
     qutebrowser \
     scrot shellcheck \
     tmux tshark wireshark-qt xautolock

# special song and dance for docker
sudo apt-get install -y \
     apt-transport-https
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
sudo apt-get install docker-ce docker-ce-cli containerd.io

# special song and dance for keybase
curl -s https://prerelease.keybase.io/keybase_amd64.deb -o /tmp/kb.deb
sudo dpkg -i /tmp/kb.deb || true
sudo apt-get install -fy

# snap is nice if it works
# the docker snap is sadly broken
sudo snap install chromium firefox opera spotify
sudo snap install intellij-idea-community --classic

# edit /etc/default/nodm to have these lines
# NODM_ENABLED=true
# NODM_USER=masse
# NODM_XSESSION=/home/masse/.xsession

# get my stuff
[ ! -e ~/.git ] &&
    cd /tmp && \
	rm -rf dotfiles.kubuntu && \
	git clone https://github.com/massemanet/dotfiles.kubuntu && \
	cd dotfiles.kubuntu && \
	git remote set-url origin git@github.com:massemanet/dotfiles.kubuntu && \
	mv /tmp/dotfiles.kubuntu/.git ~
(cd && git reset --hard)

# emacs (cask)
[ ! -d ~/.cask ] && \
    curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
(cd ~/.emacs.d && ~/.cask/bin/cask install)
